### SVVAMP

In [6]:
import svvamp as sv

In [108]:
pop = sv.PopulationSpheroid(V=5, C=3)

In [109]:
pop.labels_candidates = ["Alice", "Bob", "Chad"]

In [110]:
pop.V, pop.C, pop.labels_candidates

(5, 3, ['Alice', 'Bob', 'Chad'])

In [111]:
pop.preferences_borda_rk

array([[2, 0, 1],
       [2, 1, 0],
       [1, 0, 2],
       [1, 0, 2],
       [0, 1, 2]])

In [12]:
pop.ensure_voters_sorted_by_rk()

In [13]:
pop.preferences_rk

array([[0, 3, 2, 1],
       [1, 0, 2, 3],
       [1, 2, 0, 3],
       [1, 3, 2, 0],
       [2, 0, 1, 3],
       [2, 1, 0, 3],
       [2, 3, 1, 0],
       [3, 0, 1, 2],
       [3, 2, 0, 1],
       [3, 2, 1, 0]])

In [50]:
pop.total_utility_c

array([-0.97184396,  0.2537266 , -0.20009453,  4.45732665])

In [51]:
pop.plurality_scores_rk

array([3, 6, 4, 7])

In [52]:
pop.borda_score_c_ut

array([25., 30., 27., 38.])

In [54]:
election = sv.IRV(pop)

In [55]:
election.meets_Condorcet_c_rk

False

In [58]:
election.meets_IIA

False

### WHALRUS

In [4]:
from whalrus import *

In [112]:
profile = Profile(pop.preferences_rk.tolist())

In [113]:
profile

Profile(ballots=[BallotOrder([0, 2, 1], candidates={0, 1, 2}), BallotOrder([0, 1, 2], candidates={0, 1, 2}), BallotOrder([2, 0, 1], candidates={0, 1, 2}), BallotOrder([2, 0, 1], candidates={0, 1, 2}), BallotOrder([2, 1, 0], candidates={0, 1, 2})], weights=[1, 1, 1, 1, 1], voters=[None, None, None, None, None])

In [26]:
pop.preferences_rk

array([[0, 3, 2, 1],
       [1, 0, 2, 3],
       [1, 2, 0, 3],
       [1, 3, 2, 0],
       [2, 0, 1, 3],
       [2, 1, 0, 3],
       [2, 3, 1, 0],
       [3, 0, 1, 2],
       [3, 2, 0, 1],
       [3, 2, 1, 0]])

In [279]:
candidate_map = dict(zip(range(len(pop.labels_candidates)), pop.labels_candidates))
candidate_map

{0: 'Alice', 1: 'Bob', 2: 'Chad'}

In [115]:
test_ballot = list(map(candidate_map.get, pop.preferences_rk[0], pop.preferences_rk[0]))

In [331]:
ordered_prof = []

for ballot in pop.preferences_rk:
    ordered_ballot = {}
    for candidate, rank in zip(pop.labels_candidates, ballot):
        ordered_ballot[candidate] = rank
        
    ordered_prof.append(ordered_ballot)

In [332]:
ordered_prof

[{'Alice': 0, 'Bob': 2, 'Chad': 1},
 {'Alice': 0, 'Bob': 1, 'Chad': 2},
 {'Alice': 2, 'Bob': 0, 'Chad': 1},
 {'Alice': 2, 'Bob': 0, 'Chad': 1},
 {'Alice': 2, 'Bob': 1, 'Chad': 0}]

In [116]:
test_pop = [list(map(candidate_map.get, pop.preferences_rk[i], pop.preferences_rk[i])) for i in range(len(pop.preferences_rk))]

In [117]:
test_pop

[['Alice', 'Chad', 'Bob'],
 ['Alice', 'Bob', 'Chad'],
 ['Chad', 'Alice', 'Bob'],
 ['Chad', 'Alice', 'Bob'],
 ['Chad', 'Bob', 'Alice']]

In [121]:
test_pop1 = ['Alice > Chad > Bob',
 'Alice > Bob > Chad',
 'Chad > Alice > Bob',
 'Chad > Alice > Bob',
 'Chad > Bob > Alice']

In [118]:
profile_1 = Profile(test_pop)

In [228]:
print(profile_1)

Alice > Chad > Bob
Alice > Bob > Chad
Chad > Alice > Bob
Chad > Alice > Bob
Chad > Bob > Alice


In [119]:
profile_1

Profile(ballots=[BallotOrder(['Alice', 'Chad', 'Bob'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Alice', 'Bob', 'Chad'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Chad', 'Alice', 'Bob'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Chad', 'Alice', 'Bob'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Chad', 'Bob', 'Alice'], candidates={'Alice', 'Bob', 'Chad'})], weights=[1, 1, 1, 1, 1], voters=[None, None, None, None, None])

In [122]:
profile_2 = Profile(test_pop1)

In [123]:
profile_2

Profile(ballots=[BallotOrder(['Alice', 'Chad', 'Bob'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Alice', 'Bob', 'Chad'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Chad', 'Alice', 'Bob'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Chad', 'Alice', 'Bob'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Chad', 'Bob', 'Alice'], candidates={'Alice', 'Bob', 'Chad'})], weights=[1, 1, 1, 1, 1], voters=[None, None, None, None, None])

In [124]:
borda = RuleBorda(profile_2)

In [125]:
borda.gross_scores_

{'Alice': 6, 'Bob': 2, 'Chad': 7}

In [126]:
borda.weights_

{'Alice': 5, 'Bob': 5, 'Chad': 5}

In [145]:
profile_2.ballots[0].as_weak_order[::-1]

[{'Bob'}, {'Chad'}, {'Alice'}]

In [180]:
positional_scorer = ScorerPositional(profile_2.ballots[0], candidates = profile_2.ballots[0].candidates, points_scheme = [10, 5, 3, 0])

In [181]:
borda_scorer = ScorerBorda(profile_2.ballots[0], candidates = profile_2.ballots[0].candidates)

In [182]:
borda_scorer.candidates_

{'Alice', 'Bob', 'Chad'}

In [183]:
borda_scorer.scores_

{'Alice': 2, 'Bob': 0, 'Chad': 1}

In [184]:
positional_scorer.scores_

{'Alice': 10, 'Bob': 3, 'Chad': 5}

In [189]:
pos_rule = RuleScorePositional(profile_2, points_scheme = [10, 5, 3])

In [201]:
pos_rule.gross_scores_

{'Alice': 33, 'Bob': 19, 'Chad': 38}

In [203]:
pos_rule.scores_

{'Alice': Fraction(33, 5), 'Bob': Fraction(19, 5), 'Chad': Fraction(38, 5)}

In [204]:
pos_rule.scores_as_floats_

{'Alice': 6.6, 'Bob': 3.8, 'Chad': 7.6}

### Merging everything

In [262]:
import pandas as pd
import numpy as np

In [369]:
def label_profile(profile, candidates):
    # Convert profile to a list of {candidate: rank} per voter
    ordered_prof = []

    for ballot in profile:
        ordered_ballot = {}
        for candidate, rank in zip(candidates, ballot):
            ordered_ballot[candidate] = rank

        ordered_prof.append(ordered_ballot)
    
    sorted_dicts = [dict(sorted(profile.items(), key=lambda kv: kv[1])) for profile in ordered_prof]
    sorted_dict_keys = [list(d.keys()) for d in sorted_dicts]
    
    return sorted_dicts, sorted_dict_keys
    
def digest_profile(profile, candidates):
    
    # Matrix representation of profile, matrix[c][r] represent the frequency of candidate c in rank r
    matrix_rank = [[0]*len(profile[0]) for _ in profile[0]]
    
    # Fill out matrix rank:
    for ballot in profile:
        for j, rank in enumerate(ballot):
            matrix_rank[j][rank] += 1
    
    return np.array(matrix_rank)

def show_profile(matrix_rank, candidates):
    data_dict = {}
    
    # Create dictionary for dataframe
    data_dict["Candidates"] = candidates
    for i in range(len(matrix_rank)):
        data_dict[f"{i}th rank"] = matrix_rank[:, i]
        
    df = pd.DataFrame(data_dict)
    print(df)
    
    return df

In [438]:
profile_dicts, sorted_ranks = label_profile(pop.preferences_rk, pop.labels_candidates)
matrix_rank = digest_profile(pop.preferences_rk, pop.labels_candidates)
df = show_profile(matrix_rank, pop.labels_candidates)

  Candidates  0th rank  1th rank  2th rank
0      Alice         2         0         3
1        Bob         2         2         1
2       Chad         1         3         1


In [439]:
profile_dicts, sorted_ranks

([{'Alice': 0, 'Chad': 1, 'Bob': 2},
  {'Alice': 0, 'Bob': 1, 'Chad': 2},
  {'Bob': 0, 'Chad': 1, 'Alice': 2},
  {'Bob': 0, 'Chad': 1, 'Alice': 2},
  {'Chad': 0, 'Bob': 1, 'Alice': 2}],
 [['Alice', 'Chad', 'Bob'],
  ['Alice', 'Bob', 'Chad'],
  ['Bob', 'Chad', 'Alice'],
  ['Bob', 'Chad', 'Alice'],
  ['Chad', 'Bob', 'Alice']])

In [440]:
Profile(sorted_ranks)

Profile(ballots=[BallotOrder(['Alice', 'Chad', 'Bob'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Alice', 'Bob', 'Chad'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Bob', 'Chad', 'Alice'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Bob', 'Chad', 'Alice'], candidates={'Alice', 'Bob', 'Chad'}), BallotOrder(['Chad', 'Bob', 'Alice'], candidates={'Alice', 'Bob', 'Chad'})], weights=[1, 1, 1, 1, 1], voters=[None, None, None, None, None])

In [430]:
def create_profile(n_voters, candidates, pop_type="spheroid"):
    
    # Create a population object
    pop = sv.PopulationSpheroid(V=n_voters, C=len(candidates))
    pop.labels_candidates = candidates
        
    # Show the ranks
    matrix_rank = digest_profile(pop.preferences_rk, pop.labels_candidates)
    df_rank = show_profile(matrix_rank, pop.labels_candidates)
    
    # Create a labeled version of the ranking from the population
    profile_dicts, labeled_ranks = label_profile(pop.preferences_rk, pop.labels_candidates)
   
    # Create a profile object - automatically creates ordered ballots
    return Profile(labeled_ranks)
    
def election(profile, weights=None):
    
    # Initialize rule
    if not weights:
        raise Exception("Must insert weights!")
    else:
        rule = RuleScorePositional(profile, points_scheme=weights)
        
        print("Candidates:", rule.candidates_)
        print("Gross scores:", rule.gross_scores_)
        print("Average scores:", rule.scores_)
        print("Scores as floats:", rule.scores_as_floats_)
        print("Winner(s):", rule.cowinners_)
        
        return rule.cowinners_
    

In [445]:
profile = create_profile(6821, ["Bernie", "Warren", "Yang", "Biden"])

  Candidates  0th rank  1th rank  2th rank  3th rank
0     Bernie      1678      1736      1676      1731
1     Warren      1788      1668      1748      1617
2       Yang      1742      1661      1681      1737
3      Biden      1613      1756      1716      1736


In [446]:
election(profile, weights=[4.5, 4.4, 4.3, 4.2])

Candidates: {'Bernie', 'Biden', 'Warren', 'Yang'}
Gross scores: {'Bernie': Fraction(148332, 5), 'Biden': Fraction(296549, 10), 'Warren': Fraction(29693, 1), 'Yang': Fraction(296711, 10)}
Average scores: {'Bernie': Fraction(148332, 34105), 'Biden': Fraction(296549, 68210), 'Warren': Fraction(29693, 6821), 'Yang': Fraction(296711, 68210)}
Scores as floats: {'Bernie': 4.3492742999560186, 'Biden': 4.347588330156868, 'Warren': 4.353174021404486, 'Yang': 4.3499633484826274}
Winner(s): {'Warren'}


In [447]:
condorcet = RuleCondorcet(profile)

In [455]:
condorcet.order_

[{'Warren'}, {'Bernie', 'Biden', 'Yang'}]